### ISSUE TITLE
glitched artifacts when cursor is at specific/random positions of the screen

### ISSUE THREAD

**Issue by sewnie** [phillbush/ctrlmenu#2] opened 2023-01-13 15:16 UTC
https://user-images.githubusercontent.com/47404953/212354401-cf0078f5-e19b-4ddf-8bb6-d734c230cd7f.mp4

**Comment by phillbush** [comment] 2023-01-13 21:57
I committed a bunch of changes accumulated in the last weeks.
Does it work now?

**Comment by sewnie** [comment] 2023-01-15 05:15
Yes.

**Comment by sewnie** [comment] 2023-01-15 05:34
No.

**Comment by sewnie** [comment] 2023-01-15 05:35
https://user-images.githubusercontent.com/47404953/212524583-22274426-7121-43f0-967c-6754101c8a5f.mp4

**Comment by sewnie** [comment] 2023-01-15 06:04
https://user-images.githubusercontent.com/47404953/212525468-08304444-16ff-43ae-ac44-3e924bfdf861.mp4

this time, it is very consistent; in context mode.

**Comment by sewnie** [comment] 2023-01-15 20:05
Alas! this is actually a shod bug. please move to shod.

**Comment by sewnie** [comment] 2023-01-15 20:15
I'm not entirely sure if this is actually a shod bug. I saw a window that had the same effect under shod. But yet again the original video of this issue was taken on dwm, so I'm not exactly sure.

**Comment by phillbush** [comment] 2023-01-15 22:35
Have you changed `.triangle_width` or `.triangle_height` on `config.c`?
Which changes have you done in `config.c`?

**Comment by phillbush** [comment] 2023-01-15 23:03
It seems to be the case.

An entry that triggers a submenu has a triangle at the right of it (just like the hierarchical menus of GTK+ and QT toolkits).
The size of the triangle is configured on `config.c`.
In your videos, there are no triangles, and the glitch only happens on a menu that has such submenu-triggering entries; and only next to such entries.  I tried to set `.triangle_width` and `.triangle_height` to high values and the glitch happens here.

![menu](https://user-images.githubusercontent.com/63266536/212572094-5c75b293-3d4f-4df0-8bba-055d946dc92b.png)

I'm removing those options from `config.c` for being set at compile time; they are now computed at runtime from the font size.

**Closed as completed by phillbush** 2023-01-15 23:03 UTC

**Comment by sewnie** [comment] 2023-01-16 06:15
the issue still occurs

**Comment by sewnie** [comment] 2023-01-16 06:16
https://user-images.githubusercontent.com/47404953/212610594-38be031b-c7fa-488c-b6c7-d116a9e7b7bf.mp4

**Comment by phillbush** [comment] 2023-01-16 10:33
That's weird. The error seems to be caused by the drawing of the triangle.

Which changes have you made to the code (like, in `config.c`)?
Does the error still occur out of the box (with no change at al)?

**Comment by sewnie** [comment] 2023-01-16 10:36
>Which changes have you made to the code (like, in config.c)?

None. i'm building straight from git respository - as seen in the screenshot.

> Does the error still occur out of the box (with no change at al)?

What do you mean

**Comment by phillbush** [comment] 2023-01-16 10:59
> What do you mean

I wanted to know whether the bug still occur with no changes in the code at all.

Does the error still occur on the last commit?

**Comment by sewnie** [comment] 2023-01-16 11:04
> Does the error still occur on the last commit?

09cbf47 (HEAD), Yes; but the resulting artifacts are slightly different.

https://user-images.githubusercontent.com/47404953/212663442-197f6ebb-5566-41c5-afa0-ac136f339029.mp4

`ctrlmenu` in the monospace font is the orignal, which was before 09cbf47 (HEAD). `ctrlmenu` in the sans font is the latest HEAD.
